### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by J-C-L-G** [J-C-L-G/Kakachu#1]
Create the functions to be executed when the enemy is inside kakachu's range.

*onRange - function to be executed with every update on the enemy, must return true if the distance between the enemy and kakachu is equal or less than 100 px;

*isColliding - function to be executed if onRange function returned true, must check on the 3 or 4 corners of the enemy (square or triangle figure) if one of the 3 kakachu's coordinate is inside this enemy and call the gameOver function (not yet created).

**Comment by jenriquez90** [comment]
Solved.
